# Data Preprocessing Tools

## ライブラリのインポート

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## データセットのインポート

In [5]:
dataset = pd.read_csv(r"C:\Users\bldyr\OneDrive\デスクトップ\自己研鑽用\02_FT勉強会\2023年度\勉強会\1_データ前処理\Data.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [14]:
dataset.dropna()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [28]:
dataset = dataset["Add_columns"]

ValueError: No axis named 1 for object type Series

In [32]:
dataset = dataset.dropna(axis = 1, how = "all")

In [35]:
dict_ = dict(Age = 1, Salary = dataset["Salary"].mean())
dataset.fillna(dict_)

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain   1.0  52000.000000        No
7   France  48.0  79000.000000       Yes
8  Germany  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes

In [27]:
dataset.dropna(how = "any")

Empty DataFrame
Columns: [Country, Age, Salary, Purchased, Add_columns]
Index: []

## 欠損値の処理

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [38]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], "k2": [1, 1, 2, 3, 3, 4, 4]})
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [41]:
data["v1"] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [43]:
data.drop_duplicates(subset=["k1", "k2"], keep = "last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [44]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", "pastrami", "corned beef", "bacon","pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]}
                     )

In [47]:
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}
data["animal"] = data["food"].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [49]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [53]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [54]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [55]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [56]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [57]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [58]:
pd.value_counts(age_categories)

C:\Users\bldyr\AppData\Local\Temp\ipykernel_21848\3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [59]:
data = np.random.uniform(size = 20)
pd.cut(data, 4, precision = 2)

[(0.28, 0.51], (0.51, 0.74], (0.049, 0.28], (0.51, 0.74], (0.28, 0.51], ..., (0.74, 0.97], (0.28, 0.51], (0.049, 0.28], (0.51, 0.74], (0.74, 0.97]]
Length: 20
Categories (4, interval[float64, right]): [(0.049, 0.28] < (0.28, 0.51] < (0.51, 0.74] < (0.74, 0.97]]

In [60]:
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision=2)
quartiles

[(-2.8899999999999997, -0.68], (0.78, 2.77], (-0.68, 0.074], (0.074, 0.78], (-0.68, 0.074], ..., (-2.8899999999999997, -0.68], (-2.8899999999999997, -0.68], (-0.68, 0.074], (-0.68, 0.074], (-2.8899999999999997, -0.68]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.8899999999999997, -0.68] < (-0.68, 0.074] < (0.074, 0.78] < (0.78, 2.77]]

In [61]:
pd.value_counts(quartiles)

C:\Users\bldyr\AppData\Local\Temp\ipykernel_21848\3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-2.8899999999999997, -0.68]    250
(-0.68, 0.074]                  250
(0.074, 0.78]                   250
(0.78, 2.77]                    250
Name: count, dtype: int64

In [62]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.884, -1.235]    100
(-1.235, 0.074]     400
(0.074, 1.419]      400
(1.419, 2.765]      100
Name: count, dtype: int64

In [63]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.013959     0.011168    -0.047576    -0.007724
std       0.982125     0.994003     1.020421     1.013413
min      -3.157201    -3.048680    -3.597782    -3.237926
25%      -0.672349    -0.638698    -0.758134    -0.678610
50%      -0.009461     0.038320    -0.036897    -0.040791
75%       0.700541     0.668278     0.657781     0.694953
max       3.736177     2.855507     3.087588     3.673355

In [64]:
col = data[2]
col[col.abs() > 3]

84    -3.597782
209   -3.102854
562   -3.249428
853    3.087588
966   -3.005327
Name: 2, dtype: float64

In [65]:
data[(data.abs() > 3).any(axis = "columns")]

0         1         2         3
84   0.917371 -1.031307 -3.597782  0.000356
87  -0.567464  0.574795  1.450173  3.673355
209 -0.166370  0.320861 -3.102854 -1.084262
243 -1.028166 -3.022640 -1.607621  0.307323
387 -0.247864  0.288069  2.416389  3.352794
409 -3.137683 -0.584984 -1.760871  1.277876
457  0.312159 -0.289153 -0.359738  3.289242
559 -0.212269 -0.445099  0.794844 -3.027273
562 -0.996702 -0.233496 -3.249428  0.611946
836 -1.193795  0.891031 -0.637199 -3.237926
841 -3.157201  0.359390 -0.372935 -0.673784
853 -1.244219  1.270160  3.087588 -0.701046
953 -0.416744 -3.048680  0.541636  0.265387
966  1.152165 -0.518269 -3.005327  1.245560
981  3.736177  2.062222 -0.727958  0.169162

In [68]:
data[data.abs() > 3] = np.sign(data) * 3
data[(data.abs() > 3).any(axis = "columns")]

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [69]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.013518     0.011240    -0.046708    -0.008774
std       0.978674     0.993786     1.017172     1.008353
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.672349    -0.638698    -0.758134    -0.678610
50%      -0.009461     0.038320    -0.036897    -0.040791
75%       0.700541     0.668278     0.657781     0.694953
max       3.000000     2.855507     3.000000     3.000000

In [70]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0 -1.0
1  1.0 -1.0  1.0 -1.0
2 -1.0 -1.0  1.0 -1.0
3 -1.0  1.0  1.0  1.0
4 -1.0 -1.0 -1.0 -1.0

In [71]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [75]:
sampler = np.random.permutation(5)
sampler

array([3, 2, 0, 4, 1])

In [78]:
samplar_col = np.random.permutation(7)
samplar_col

array([0, 6, 4, 1, 3, 5, 2])

In [79]:
df.take(samplar_col, axis = 1)

0   6   4   1   3   5   2
0   0   6   4   1   3   5   2
1   7  13  11   8  10  12   9
2  14  20  18  15  17  19  16
3  21  27  25  22  24  26  23
4  28  34  32  29  31  33  30

In [76]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [77]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [80]:
df = pd.DataFrame({"カテゴリ変数": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
df

カテゴリ変数  data1
0      b      0
1      b      1
2      a      2
3      c      3
4      a      4
5      b      5

In [82]:
pd.get_dummies(df["カテゴリ変数"])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [83]:
dummies = pd.get_dummies(df["カテゴリ変数"], prefix = "カテゴリ変数")
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

data1  カテゴリ変数_a  カテゴリ変数_b  カテゴリ変数_c
0      0     False      True     False
1      1     False      True     False
2      2      True     False     False
3      3     False     False      True
4      4      True     False     False
5      5     False      True     False

In [85]:
movies = pd.read_csv(r"C:\Users\bldyr\OneDrive\デスクトップ\自己研鑽用\02_FT勉強会\2023年度\勉強会\movies_data.csv", engine = "python")
movies

movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
1927      1996              Poltergeist III (1988)   
1928      1997                Exorcist, The (1973)   
1929      1998                         Exorcist II   
1930      1999            Exorcist III, The (1990)   
1931      2000                Lethal Weapon (1987)   

                            genres  
0      Animation|Children's|Comedy  
1     Adventure|Children's|Fantasy  
2                   Comedy|Romance  
3                     Comedy|Drama  
4                           Comedy  
...                            ...  
1927               Horror|Thriller  
1928                        Horror  
1929                        Horror  
1930                        Horror  
1931     Action|Comedy|Crime|Drama  

[1932 rows x 3 columns]

In [86]:
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [87]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [88]:
val = "a,b, guido"
val.split(",")

['a', 'b', ' guido']

In [90]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [91]:
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [92]:
"::".join(pieces)

'a::b::guido'

In [93]:
"guido" in val

True

In [94]:
val.index(",")

1

In [95]:
val.find(":")

-1

In [96]:
val.index(":")

ValueError: substring not found

In [97]:
val.count(",")

2

In [98]:
val.replace(",", "::")

'a::b:: guido'

In [99]:
import re
text = "foo bar\t baz \tqux"
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [100]:
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [101]:
regex.findall(text)

[' ', '\t ', ' \t']

In [102]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [104]:
# re.IGNORECASEフラグにより，正規表現で大文字と小文字を区別しないようにする
regex = re.compile(pattern, flags=re.IGNORECASE)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [107]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [108]:
text[m.start():m.end()]

'dave@google.com'

In [109]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [111]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags = re.IGNORECASE)
m = regex.match("wesm@bright.net")
m.groups()

('wesm', 'bright', 'net')

In [112]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [113]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [118]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)
values.unique()

array(['apple', 'orange'], dtype=object)

In [117]:
pd.value_counts(values)

C:\Users\bldyr\AppData\Local\Temp\ipykernel_21848\3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     6
orange    2
Name: count, dtype: int64

In [121]:
values = pd.Series([0, 1, 0, 0] * 2)
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [122]:
dim = pd.Series(['apple', 'orange'])
dim

0     apple
1    orange
dtype: object

In [123]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [124]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                   columns = ['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [125]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [126]:
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [127]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [128]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [129]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [130]:
df['fruit'] = df['fruit'].astype('category')
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [131]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [132]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [133]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered = True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [134]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [136]:
rng = np.random.default_rng(seed = 12345)
draws = rng.standard_normal(1000)
draws

array([-1.42382504e+00,  1.26372846e+00, -8.70661738e-01, -2.59173235e-01,
       -7.53433070e-02, -7.40884652e-01, -1.36779270e+00,  6.48892802e-01,
        3.61058113e-01, -1.95286306e+00,  2.34740965e+00,  9.68496906e-01,
       -7.59387180e-01,  9.02198274e-01, -4.66953173e-01, -6.06895187e-02,
        7.88844345e-01, -1.25666813e+00,  5.75857514e-01,  1.39897899e+00,
        1.32229806e+00, -2.99698515e-01,  9.02919341e-01, -1.62158273e+00,
       -1.58189261e-01,  4.49483932e-01, -1.34360107e+00, -8.16875907e-02,
        1.72473993e+00,  2.61815943e+00,  7.77361344e-01,  8.28633196e-01,
       -9.58988313e-01, -1.20938829e+00, -1.41229201e+00,  5.41546830e-01,
        7.51939396e-01, -6.58760320e-01, -1.22867499e+00,  2.57557768e-01,
        3.12902918e-01, -1.30811690e-01,  1.26998312e+00, -9.29624577e-02,
       -6.61508890e-02, -1.10821447e+00,  1.35956851e-01,  1.34707776e+00,
        6.11440210e-02,  7.09146003e-02,  4.33654537e-01,  2.77483660e-01,
        5.30252387e-01,  

In [137]:
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [139]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index())
results

C:\Users\bldyr\AppData\Local\Temp\ipykernel_21848\1164697889.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  results = (pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index())


quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [141]:
N = 10_000_000
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))
categories = labels.astype('category')
categories

0          foo
1          bar
2          baz
3          qux
4          foo
          ... 
9999995    qux
9999996    foo
9999997    bar
9999998    baz
9999999    qux
Length: 10000000, dtype: category
Categories (4, object): ['bar', 'baz', 'foo', 'qux']

In [142]:
print(labels.memory_usage(deep = True), categories.memory_usage(deep = True))

600000128 10000540


In [143]:
%time _ = labels.astype('category')

Wall time: 923 ms


## カテゴリ変数の処理

### 独立変数のエンコーディング

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### 従属変数のエンコーディング

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

### 訓練用データセットとテストデータセットへの分割

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

In [ ]:
print(X_test)

In [ ]:
print(y_train)

In [ ]:
print(y_test)

## フィーチャースケーリング

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [ ]:
print(X_train)

In [ ]:
print(X_test)